# Generated by Django 6.0 on 2025-12-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="insurance_company",
            field=models.IntegerField(
                blank=True, help_text="Selected insurance company ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="problem_type",
            field=models.CharField(
                blank=True,
                help_text="Type of insurance problem: mediclaim, life_insurance, critical_illness, motor_insurance, marine_claim, fire_claim, or custom",
                max_length=100,
            ),
        ),
    ]
