# Generated by Django 6.0 on 2025-12-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "grievance_core",
            "0003_alter_case_insurance_company_name_insurancecompany_and_more",
        ),
        ("users", "0002_customuser_insurance_company_customuser_problem_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="insurance_company",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected insurance company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grievance_core.insurancecompany",
            ),
        ),
    ]
