# Generated by Django 6.0 on 2026-01-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_insurance_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gmail_connected",
            field=models.BooleanField(
                default=False, help_text="Whether Gmail account is connected"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gmail_email",
            field=models.EmailField(
                blank=True,
                help_text="Connected Gmail address",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gmail_refresh_token",
            field=models.TextField(
                blank=True,
                help_text="Encrypted Gmail refresh token for OAuth",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gmail_token_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When the Gmail access token expires", null=True
            ),
        ),
    ]
