# Generated by Django 6.0.1 on 2026-01-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_gmail_connected_customuser_gmail_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("complainant", "Insurance Complainant"),
                    ("ombudsman_admin", "Ombudsman Admin"),
                    ("insurance_agent", "Insurance Company Agent"),
                    ("support_staff", "Support Staff"),
                    ("medical_reviewer", "Medical Reviewer"),
                ],
                default="complainant",
                help_text="User role within the system",
                max_length=20,
            ),
        ),
    ]
