# Generated by Django 6.0.1 on 2026-01-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gmail_history_id",
            field=models.CharField(
                blank=True,
                help_text="Last known Gmail history ID for incremental sync",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gmail_watch_expiration",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Gmail Pub/Sub watch expires (needs renewal every 7 days)",
                null=True,
            ),
        ),
    ]
