# Generated by Django 6.0.1 on 2026-02-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_gmail_history_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("complainant", "Insurance Complainant"),
                    ("ombudsman_admin", "Ombudsman Admin"),
                    ("insurance_agent", "Insurance Company Agent"),
                    ("support_staff", "Support Staff"),
                    ("medical_reviewer", "Medical Reviewer"),
                    ("dispute_expert", "Dispute Review Expert"),
                ],
                default="complainant",
                help_text="User role within the system",
                max_length=20,
            ),
        ),
    ]
