# Generated by Django 6.0.1 on 2026-03-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_merge_0007"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
