# Generated by Django 6.0.1 on 2026-03-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="google_id",
            field=models.CharField(
                blank=True,
                help_text="Google account subject ID for Google OAuth login",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
