# Generated by Django 6.0 on 2025-12-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique case identifier (e.g., CC-2025-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("rejected", "Rejected"),
                            ("escalated_to_ombudsman", "Escalated to Ombudsman"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the case",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Case priority level",
                        max_length=20,
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("motor", "Motor Insurance"),
                            ("health", "Health Insurance"),
                            ("home", "Home Insurance"),
                            ("life", "Life Insurance"),
                            ("travel", "Travel Insurance"),
                            ("other", "Other"),
                        ],
                        help_text="Type of insurance policy",
                        max_length=30,
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(
                        db_index=True,
                        help_text="Insurance policy number",
                        max_length=100,
                    ),
                ),
                (
                    "insurance_company_name",
                    models.CharField(
                        help_text="Name of the insurance company", max_length=255
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the grievance", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the complaint"),
                ),
                (
                    "date_of_incident",
                    models.DateField(
                        help_text="Date when the incident/rejection occurred"
                    ),
                ),
                (
                    "date_of_rejection",
                    models.DateField(
                        blank=True,
                        help_text="Date when policy was rejected (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "draft_content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON draft of the complaint (for multi-step form)",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the case was formally submitted",
                        null=True,
                    ),
                ),
                (
                    "is_escalated_to_ombudsman",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether case has been escalated to ombudsman",
                    ),
                ),
                (
                    "escalation_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date of escalation to ombudsman",
                        null=True,
                    ),
                ),
                (
                    "resolution_date",
                    models.DateTimeField(
                        blank=True, help_text="Date case was resolved", null=True
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Notes on how the case was resolved"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "db_table": "grievance_core_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Case Created"),
                            ("status_change", "Status Changed"),
                            ("document_uploaded", "Document Uploaded"),
                            ("email_received", "Email Received"),
                            ("email_sent", "Email Sent"),
                            ("escalated", "Escalated to Ombudsman"),
                            ("comment_added", "Comment Added"),
                            ("resolved", "Case Resolved"),
                        ],
                        help_text="Type of event",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(help_text="Description of the event")),
                (
                    "old_value",
                    models.CharField(
                        blank=True,
                        help_text="Previous value (for status changes)",
                        max_length=255,
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True,
                        help_text="New value (for status changes)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Case Timeline",
                "verbose_name_plural": "Case Timelines",
                "db_table": "grievance_core_casetimeline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("data_processing", "Data Processing Consent"),
                            ("email_communication", "Email Communication"),
                            ("phone_communication", "Phone Communication"),
                            ("information_sharing", "Third-Party Information Sharing"),
                            ("terms_and_conditions", "Terms and Conditions"),
                        ],
                        help_text="Type of consent",
                        max_length=50,
                    ),
                ),
                (
                    "is_given",
                    models.BooleanField(
                        default=False, help_text="Whether consent was given"
                    ),
                ),
                (
                    "given_at",
                    models.DateTimeField(
                        blank=True, help_text="When consent was given", null=True
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When consent was revoked (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address at time of consent", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consent",
                "verbose_name_plural": "Consents",
                "db_table": "grievance_core_consent",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("policy_document", "Policy Document"),
                            ("rejection_letter", "Rejection Letter"),
                            ("support_document", "Support Document"),
                            ("communication", "Communication"),
                            ("proof_of_payment", "Proof of Payment"),
                            ("medical_report", "Medical Report"),
                            ("other", "Other"),
                        ],
                        help_text="Type of document",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File upload (local or S3)",
                        upload_to="case_documents/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(
                        help_text="MIME type (e.g., application/pdf)", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of document content"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether document has been verified by admin",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When document was verified", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "grievance_core_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        help_text="Direction of email (inbound/outbound)",
                        max_length=20,
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(help_text="Sender email address", max_length=254),
                ),
                (
                    "to_email",
                    models.EmailField(
                        help_text="Recipient email address", max_length=254
                    ),
                ),
                (
                    "cc_emails",
                    models.CharField(
                        blank=True,
                        help_text="CC recipients (comma-separated)",
                        max_length=500,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject", max_length=255),
                ),
                ("body", models.TextField(help_text="Email body content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When email was sent", null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="When email was delivered", null=True
                    ),
                ),
                (
                    "is_automated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether email was auto-generated by system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Tracking",
                "verbose_name_plural": "Email Tracking",
                "db_table": "grievance_core_emailtracking",
                "ordering": ["-created_at"],
            },
        ),
    ]
