# Generated by Django 6.0 on 2025-12-30 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grievance_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="user",
            field=models.ForeignKey(
                help_text="User who filed the complaint",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casetimeline",
            name="case",
            field=models.ForeignKey(
                help_text="Associated case",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="grievance_core.case",
            ),
        ),
        migrations.AddField(
            model_name="casetimeline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered this event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timeline_events_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="case",
            field=models.ForeignKey(
                help_text="Associated case",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to="grievance_core.case",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="user",
            field=models.ForeignKey(
                help_text="User providing consent",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="case",
            field=models.ForeignKey(
                help_text="Associated case",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="grievance_core.case",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who verified the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="case",
            field=models.ForeignKey(
                help_text="Associated case",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="grievance_core.case",
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who sent the email (if manual)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["user", "status"], name="grievance_c_user_id_989e85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["case_number"], name="grievance_c_case_nu_0fe5b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["policy_number"], name="grievance_c_policy__ea8fa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["is_escalated_to_ombudsman"],
                name="grievance_c_is_esca_df78a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["-created_at"], name="grievance_c_created_df740e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casetimeline",
            index=models.Index(
                fields=["case", "-created_at"], name="grievance_c_case_id_101e82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casetimeline",
            index=models.Index(
                fields=["event_type"], name="grievance_c_event_t_110554_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(
                fields=["user", "consent_type"], name="grievance_c_user_id_a5e950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(
                fields=["case", "consent_type"], name="grievance_c_case_id_dde82f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consent",
            unique_together={("case", "user", "consent_type")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["case", "-created_at"], name="grievance_c_case_id_9052e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="grievance_c_documen_0c50b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_verified"], name="grievance_c_is_veri_e45061_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtracking",
            index=models.Index(
                fields=["case", "-created_at"], name="grievance_c_case_id_62483b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtracking",
            index=models.Index(
                fields=["email_type", "status"], name="grievance_c_email_t_e30d84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtracking",
            index=models.Index(
                fields=["from_email"], name="grievance_c_from_em_40a222_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtracking",
            index=models.Index(
                fields=["to_email"], name="grievance_c_to_emai_159ef0_idx"
            ),
        ),
    ]
