# Generated by Django 6.0 on 2025-12-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="insurance_company_name",
            field=models.CharField(
                help_text="Name of the insurance company (legacy field, use insurance_company FK)",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("life", "Life Insurance"),
                            ("health", "Health Insurance"),
                            ("general", "General Insurance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "grievance_email",
                    models.EmailField(
                        help_text="Primary grievance email", max_length=254
                    ),
                ),
                (
                    "additional_emails",
                    models.JSONField(
                        blank=True, default=list, help_text="Additional emails as list"
                    ),
                ),
                (
                    "grievance_helpline",
                    models.CharField(
                        blank=True, help_text="Helpline numbers", max_length=500
                    ),
                ),
                (
                    "gro_email",
                    models.EmailField(
                        blank=True,
                        help_text="Grievance Redressal Officer email",
                        max_length=254,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("correspondence_address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Insurance Company",
                "verbose_name_plural": "Insurance Companies",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="grievance_c_categor_f3ac1c_idx",
                    ),
                    models.Index(fields=["name"], name="grievance_c_name_52c675_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="case",
            name="insurance_company",
            field=models.ForeignKey(
                blank=True,
                help_text="Insurance company (foreign key)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cases",
                to="grievance_core.insurancecompany",
            ),
        ),
    ]
