# Generated by Django 6.0 on 2026-01-03 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "grievance_core",
            "0003_alter_case_insurance_company_name_insurancecompany_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtracking",
            name="gmail_message_id",
            field=models.CharField(
                blank=True,
                help_text="Gmail message ID for tracking",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="gmail_thread_id",
            field=models.CharField(
                blank=True,
                help_text="Gmail thread ID for conversation tracking",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="emailtracking",
            index=models.Index(
                fields=["gmail_message_id"], name="grievance_c_gmail_m_59ac7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtracking",
            index=models.Index(
                fields=["gmail_thread_id"], name="grievance_c_gmail_t_74195f_idx"
            ),
        ),
    ]
