# Generated by Django 6.0 on 2026-01-04 16:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_core", "0004_emailtracking_gmail_message_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=cloudinary.models.CloudinaryField(
                help_text="File upload to Cloudinary",
                max_length=255,
                verbose_name="document",
            ),
        ),
    ]
