# Generated by Django 6.0.1 on 2026-01-31 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_core", "0005_alter_document_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="gmail_message_id",
            field=models.CharField(
                blank=True,
                help_text="Gmail message ID of the original grievance email",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="gmail_thread_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Gmail thread ID for tracking replies to this case",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["gmail_thread_id"], name="grievance_c_gmail_t_c15d74_idx"
            ),
        ),
    ]
