# Generated by Django 6.0.1 on 2026-02-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_core", "0007_notification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="grievance_c_user_id_212172_idx",
            old_name="grievance_c_user_id_e50c82_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="grievance_c_user_id_fb829f_idx",
            old_name="grievance_c_user_id_fc3ddc_idx",
        ),
        migrations.AlterField(
            model_name="emailtracking",
            name="body",
            field=models.TextField(
                help_text="Email body content. For inbound emails, this is not stored for privacy compliance."
            ),
        ),
    ]
