# Generated by Django 6.0.1 on 2026-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "grievance_core",
            "0008_rename_grievance_c_user_id_e50c82_idx_grievance_c_user_id_212172_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="gmail_tracking_stopped",
            field=models.BooleanField(
                default=False, help_text="Whether to stop Gmail tracking for this case"
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="is_manual_entry",
            field=models.BooleanField(
                default=False,
                help_text="Whether this reply was manually entered by user",
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="manual_entry_submitted_at",
            field=models.DateTimeField(
                blank=True, help_text="When the manual entry was submitted", null=True
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="reply_body",
            field=models.TextField(
                blank=True, help_text="Manually entered reply body content", null=True
            ),
        ),
    ]
