# Generated by Django 6.0.1 on 2026-02-12 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_core", "0009_case_gmail_tracking_stopped_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtracking",
            name="admin_decision",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("claim_accepted", "Claim Accepted"),
                    ("claim_rejected", "Claim Rejected"),
                ],
                default="pending",
                help_text="Admin's decision on the manually entered reply",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="admin_decision_at",
            field=models.DateTimeField(
                blank=True, help_text="When admin made the decision", null=True
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="admin_decision_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who made the decision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailtracking",
            name="admin_decision_notes",
            field=models.TextField(
                blank=True, help_text="Admin's notes/reasoning for the decision"
            ),
        ),
    ]
