# Generated by Django 6.0.1 on 2026-02-12 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_core", "0010_emailtracking_admin_decision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OmbudsmanGuideProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1, help_text="Current step number (1-15)"
                    ),
                ),
                (
                    "completed_steps",
                    models.JSONField(
                        default=list, help_text="Array of completed step numbers"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Whether user has completed all steps"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the guide was completed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        help_text="Case this progress is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ombudsman_guide_progress",
                        to="grievance_core.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User viewing the guide",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ombudsman_guide_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ombudsman Guide Progress",
                "verbose_name_plural": "Ombudsman Guide Progress",
                "db_table": "grievance_core_ombudsman_guide_progress",
                "indexes": [
                    models.Index(
                        fields=["case", "user"], name="grievance_c_case_id_c45c73_idx"
                    ),
                    models.Index(
                        fields=["is_completed"], name="grievance_c_is_comp_f36cda_idx"
                    ),
                ],
                "unique_together": {("case", "user")},
            },
        ),
    ]
