# Generated by Django 6.0.1 on 2026-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_core", "0011_ombudsmanguideprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtracking",
            name="from_email",
            field=models.CharField(
                help_text="Sender email address (can include display name: 'Name <email@example.com>')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="emailtracking",
            name="to_email",
            field=models.CharField(
                help_text="Recipient email address (can include display name: 'Name <email@example.com>')",
                max_length=255,
            ),
        ),
    ]
