# Generated by Django 6.0.1 on 2026-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocument",
            name="content",
            field=models.TextField(
                help_text="Paste your document content here. If content_format is HTML, paste raw HTML. If content_format is Plain Text, paste the document as-is."
            ),
        ),
        migrations.AlterField(
            model_name="legaldocument",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Check this to make this version the one shown to users. Activating this will automatically deactivate the previous active version.",
            ),
        ),
        migrations.AlterField(
            model_name="legaldocument",
            name="version",
            field=models.CharField(
                default="1.0",
                help_text='Version label shown to users, e.g. "2.1" or "March 2026"',
                max_length=50,
            ),
        ),
    ]
