# Generated by Django 6.0.1 on 2026-01-15 11:48

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name (e.g., lucide icon)",
                        max_length=100,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in lists"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (leave empty for top-level categories)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="consumer_disputes.disputecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute Category",
                "verbose_name_plural": "Dispute Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ConsumerDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispute_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated dispute ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the dispute", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the issue"),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Order ID, Booking ID, or any reference number",
                        max_length=255,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        blank=True, help_text="Date of transaction/incident", null=True
                    ),
                ),
                (
                    "amount_involved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount in dispute (if applicable)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Call"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_contact_time",
                    models.CharField(
                        blank=True,
                        help_text="Preferred time to contact (e.g., 'Morning', '10 AM - 2 PM')",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, help_text="Internal notes for team"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team member handling this dispute",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who submitted the dispute",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Main category of the dispute",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="consumer_disputes.disputecategory",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sub-category (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategory_disputes",
                        to="consumer_disputes.disputecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumer Dispute",
                "verbose_name_plural": "Consumer Disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="dispute_document"
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt/Invoice"),
                            ("screenshot", "Screenshot"),
                            ("email", "Email Correspondence"),
                            ("contract", "Contract/Agreement"),
                            ("id_proof", "ID Proof"),
                            ("bank_statement", "Bank Statement"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="consumer_disputes.consumerdispute",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_dispute_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute Document",
                "verbose_name_plural": "Dispute Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Dispute Created"),
                            ("status_change", "Status Changed"),
                            ("note_added", "Note Added"),
                            ("contact_attempted", "Contact Attempted"),
                            ("document_uploaded", "Document Uploaded"),
                            ("assigned", "Assigned to Team Member"),
                            ("resolved", "Dispute Resolved"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="consumer_disputes.consumerdispute",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispute_timeline_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute Timeline",
                "verbose_name_plural": "Dispute Timeline Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="logo"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Admin verified entity"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Categories this entity belongs to",
                        related_name="entities",
                        to="consumer_disputes.disputecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="consumerdispute",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific entity/company (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes",
                to="consumer_disputes.entity",
            ),
        ),
        migrations.AddIndex(
            model_name="disputecategory",
            index=models.Index(
                fields=["parent", "is_active"], name="consumer_di_parent__09641d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputecategory",
            index=models.Index(fields=["slug"], name="consumer_di_slug_4b7627_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["name"], name="consumer_di_name_d3c3a7_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(fields=["slug"], name="consumer_di_slug_baa9e1_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["is_active"], name="consumer_di_is_acti_1837b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumerdispute",
            index=models.Index(
                fields=["dispute_id"], name="consumer_di_dispute_f5a2f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumerdispute",
            index=models.Index(fields=["status"], name="consumer_di_status_244dcd_idx"),
        ),
        migrations.AddIndex(
            model_name="consumerdispute",
            index=models.Index(fields=["user"], name="consumer_di_user_id_58a440_idx"),
        ),
        migrations.AddIndex(
            model_name="consumerdispute",
            index=models.Index(
                fields=["category"], name="consumer_di_categor_2d6c92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumerdispute",
            index=models.Index(
                fields=["created_at"], name="consumer_di_created_5b8cf1_idx"
            ),
        ),
    ]
