# Generated by Django 6.0.1 on 2026-02-01 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer_disputes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Professional license/certification number",
                        max_length=100,
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of experience in dispute resolution"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Expert's background and expertise"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the expert is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for the expert",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Profile",
                "verbose_name_plural": "Expert Profiles",
                "db_table": "consumer_disputes_expert_profile",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="DisputeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_review", "In Review"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the assignment",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level of the review",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Assignment notes or special instructions"
                    ),
                ),
                (
                    "review_summary",
                    models.TextField(
                        blank=True, help_text="Expert's overall review summary"
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("needs_info", "Needs More Information"),
                            ("escalate", "Escalate"),
                        ],
                        help_text="Expert's recommendation",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When expert started the review",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When review was completed", null=True
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Admin who created the assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expert_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        help_text="Consumer dispute being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_assignments",
                        to="consumer_disputes.consumerdispute",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        help_text="Expert assigned to review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="consumer_disputes.expertprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute Assignment",
                "verbose_name_plural": "Dispute Assignments",
                "db_table": "consumer_disputes_assignment",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeDocumentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("needs_clarification", "Needs Clarification"),
                        ],
                        default="pending",
                        help_text="Review status",
                        max_length=30,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Expert's comments on the document"
                    ),
                ),
                (
                    "is_authentic",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether document appears authentic",
                        null=True,
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low Confidence"),
                            ("medium", "Medium Confidence"),
                            ("high", "High Confidence"),
                        ],
                        help_text="Expert's confidence in the review",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Assignment this review belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_reviews",
                        to="consumer_disputes.disputeassignment",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_reviews",
                        to="consumer_disputes.disputedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Review",
                "verbose_name_plural": "Document Reviews",
                "db_table": "consumer_disputes_document_review",
                "ordering": ["-reviewed_at"],
                "indexes": [
                    models.Index(
                        fields=["assignment", "status"],
                        name="consumer_di_assignm_fd106c_idx",
                    ),
                    models.Index(
                        fields=["document"], name="consumer_di_documen_9ddb46_idx"
                    ),
                ],
                "unique_together": {("assignment", "document")},
            },
        ),
        migrations.AddIndex(
            model_name="disputeassignment",
            index=models.Index(
                fields=["expert", "status"], name="consumer_di_expert__21c4b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeassignment",
            index=models.Index(
                fields=["dispute", "status"], name="consumer_di_dispute_ab71f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeassignment",
            index=models.Index(
                fields=["-assigned_at"], name="consumer_di_assigne_ed872d_idx"
            ),
        ),
    ]
