# Generated by Django 6.0.1 on 2026-01-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grievance_core", "0005_alter_document_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to="grievance_core.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Document",
                "verbose_name_plural": "Assignment Documents",
                "db_table": "medical_review_assignment_document",
            },
        ),
        migrations.CreateModel(
            name="MedicalReviewerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the medical reviewer", max_length=255
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("general_medicine", "General Medicine"),
                            ("cardiology", "Cardiology"),
                            ("orthopedics", "Orthopedics"),
                            ("neurology", "Neurology"),
                            ("oncology", "Oncology"),
                            ("pediatrics", "Pediatrics"),
                            ("surgery", "General Surgery"),
                            ("radiology", "Radiology"),
                            ("pathology", "Pathology"),
                            ("psychiatry", "Psychiatry"),
                            ("dermatology", "Dermatology"),
                            ("ophthalmology", "Ophthalmology"),
                            ("ent", "ENT"),
                            ("gynecology", "Gynecology"),
                            ("urology", "Urology"),
                            ("pulmonology", "Pulmonology"),
                            ("gastroenterology", "Gastroenterology"),
                            ("nephrology", "Nephrology"),
                            ("endocrinology", "Endocrinology"),
                            ("other", "Other"),
                        ],
                        help_text="Medical specialization",
                        max_length=50,
                    ),
                ),
                (
                    "other_specialization",
                    models.CharField(
                        blank=True,
                        help_text="If specialization is 'other', specify here",
                        max_length=100,
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of medical practice"
                    ),
                ),
                (
                    "is_onboarded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether reviewer has completed onboarding",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether reviewer is available for new assignments",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Reviewer Profile",
                "verbose_name_plural": "Medical Reviewer Profiles",
                "db_table": "medical_review_profile",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="ReviewAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("needs_more_info", "Needs More Information"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Notes from admin to reviewer"
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When reviewer started the review",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When review was completed", null=True
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Admin who assigned this review",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="Associated case",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to="grievance_core.case",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="Assigned medical reviewer",
                        limit_choices_to={"role": "medical_reviewer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Assignment",
                "verbose_name_plural": "Review Assignments",
                "db_table": "medical_review_assignment",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_more_info", "Needs More Information"),
                        ],
                        help_text="Review outcome",
                        max_length=20,
                    ),
                ),
                (
                    "comments",
                    models.TextField(help_text="Detailed comments and observations"),
                ),
                (
                    "additional_info_requested",
                    models.TextField(
                        blank=True,
                        help_text="If outcome is 'needs_more_info', specify what's needed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_document",
                    models.ForeignKey(
                        help_text="The document being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="medical_review.assignmentdocument",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="Reviewer who made this review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Parent assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="medical_review.reviewassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Review",
                "verbose_name_plural": "Document Reviews",
                "db_table": "medical_review_document_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="assignmentdocument",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="medical_review.reviewassignment",
            ),
        ),
        migrations.CreateModel(
            name="ReviewerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_assignments", models.PositiveIntegerField(default=0)),
                ("pending_assignments", models.PositiveIntegerField(default=0)),
                ("completed_assignments", models.PositiveIntegerField(default=0)),
                ("total_documents_reviewed", models.PositiveIntegerField(default=0)),
                ("approved_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("needs_info_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_review_time_hours",
                    models.FloatField(
                        default=0,
                        help_text="Average time to complete a review in hours",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "reviewer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviewer Statistics",
                "verbose_name_plural": "Reviewer Statistics",
                "db_table": "medical_review_stats",
            },
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["reviewer", "status"], name="medical_rev_reviewe_807042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["case", "-assigned_at"], name="medical_rev_case_id_f701bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentreview",
            index=models.Index(
                fields=["assignment", "outcome"], name="medical_rev_assignm_6c995b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentreview",
            index=models.Index(
                fields=["reviewer", "-created_at"],
                name="medical_rev_reviewe_0b2067_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentreview",
            unique_together={("assignment_document", "reviewer")},
        ),
        migrations.AlterUniqueTogether(
            name="assignmentdocument",
            unique_together={("assignment", "document")},
        ),
    ]
